In [13]:
import pandas as pd
shop=pd.read_excel("shop_new.xlsx",None)
order=shop['订单信息']
customer=shop['顾客信息']
good=shop['货物信息']
customer

        客户ID  登陆次数  经验值  订单数
0       5245    55  206    1
1       5254    69  428   13
2       5286    57  280    1
3       5292   184  643    5
4       5474    71   61    2
...      ...   ...  ...  ...
2995  169699    20  153    3
2996  169815    13   57    1
2997  169832    12   62    1
2998  169934    14   68    2
2999  169976    16   27    1

[3000 rows x 4 columns]

In [18]:
for id in customer.客户ID:
    # c1=customer.loc[customer.客户ID==id,"订单数"].values[0]
    c1=customer[customer.客户ID==id]['订单数'].values[0]
    c2=order[(order.客户ID==id)&(order.订单状态==1)].shape[0]
    if c1!=c2:
        customer.loc[customer.客户ID==id,"订单数"]=c2
customer

        客户ID  登陆次数  经验值  订单数
0       5245    55  206    1
1       5254    69  428    9
2       5286    57  280    2
3       5292   184  643    6
4       5474    71   61    2
...      ...   ...  ...  ...
2995  169699    20  153    2
2996  169815    13   57    1
2997  169832    12   62    1
2998  169934    14   68    2
2999  169976    16   27    1

[3000 rows x 4 columns]

In [2]:
order

         订单ID    客户ID  订单状态  优惠类型
0       47739    5245     1     0
1      341269    5245     0     0
2       32690    5254     1     0
3       45641    5254     1     0
4       66116    5254     1     0
...       ...     ...   ...   ...
29145  446758  169934     1     1
29146  446759  169934     1     0
29147  447165  169976     0     1
29148  447274  169976     0     1
29149  447375  169976     1     1

[29150 rows x 4 columns]

In [3]:
good

        订单ID    货物ID      货物名称 优惠额度
0     264971  103247  自然乐园水果礼盒  >15
1     264994  103247  自然乐园水果礼盒  >15
2     266829  103247  自然乐园水果礼盒  >15
3     267232  103247  自然乐园水果礼盒  >15
4     269051  103247  自然乐园水果礼盒  >15
...      ...     ...       ...  ...
3125  282903  103376   500元充值卡    0
3126  283994  103376   500元充值卡    0
3127  284171  103376   500元充值卡    0
3128  256095  103376   500元充值卡    0
3129  256499  103376   500元充值卡    0

[3130 rows x 4 columns]

In [20]:
writer=pd.ExcelWriter("shop_new2.xlsx")
customer.to_excel(writer,sheet_name="顾客信息",index=False)
order.to_excel(writer,sheet_name="订单信息",index=False)
good.to_excel(writer,sheet_name="货物信息",index=False)
writer._save()