In [9]:
import pandas as pd
import matplotlib.pyplot as plt
plt.rcParams['font.family'] = ['Microsoft YaHei','SimHei','sans-serif']
shop=pd.read_excel('shop_new2.xlsx',None)
good=shop['货物信息']
good

        订单ID    货物ID      货物名称 优惠额度
0     264971  103247  自然乐园水果礼盒  >15
1     264994  103247  自然乐园水果礼盒  >15
2     266829  103247  自然乐园水果礼盒  >15
3     267232  103247  自然乐园水果礼盒  >15
4     269051  103247  自然乐园水果礼盒  >15
...      ...     ...       ...  ...
3125  282903  103376   500元充值卡    0
3126  283994  103376   500元充值卡    0
3127  284171  103376   500元充值卡    0
3128  256095  103376   500元充值卡    0
3129  256499  103376   500元充值卡    0

[3130 rows x 4 columns]

In [11]:
good[good.优惠额度=='0'].groupby('货物名称').size().sort_values(ascending=False).head()

货物名称
海南香蕉           60
安慕希希腊酸奶（原味）    57
冷冻鲜肉           51
新希望酸奶初心        50
静宁小苹果          48
dtype: int64

In [6]:
good[good.优惠额度=='0'].groupby('货物名称').size().sort_values(ascending=False).head()

array([  5560,   5580,   5723, ..., 169815, 169832, 169976], dtype=int64)

In [7]:
customer=shop['顾客信息']
customer

        客户ID  登陆次数  经验值  订单数
0       5245    55  206    1
1       5254    69  428    9
2       5286    57  280    2
3       5292   184  643    6
4       5474    71   61    2
...      ...   ...  ...  ...
2995  169699    20  153    2
2996  169815    13   57    1
2997  169832    12   62    1
2998  169934    14   68    2
2999  169976    16   27    1

[3000 rows x 4 columns]

In [8]:
customer['客户类型']=1
customer

        客户ID  登陆次数  经验值  订单数  客户类型
0       5245    55  206    1     1
1       5254    69  428    9     1
2       5286    57  280    2     1
3       5292   184  643    6     1
4       5474    71   61    2     1
...      ...   ...  ...  ...   ...
2995  169699    20  153    2     1
2996  169815    13   57    1     1
2997  169832    12   62    1     1
2998  169934    14   68    2     1
2999  169976    16   27    1     1

[3000 rows x 5 columns]

In [ ]:
customer.loc[customer.客户ID]