In [117]:
import pandas as pd
# 一次性导入所有图例
from pyecharts.charts import * 
# 导入环境配置代码 可视化的依赖
from pyecharts.globals import CurrentConfig, NotebookType  
CurrentConfig.NOTEBOOK_TYPE = NotebookType.JUPYTER_LAB
# 配置选项 
from pyecharts import options as opts
# 主题的类型
from pyecharts.globals import ThemeType

In [118]:
a1=pd.read_excel('./大众点评.xlsx')
a1

,城市,门店名称,地址,品类,营业时间,门店整体评分,口味评分,人均消费,招牌菜
0,上海,BELLOCO倍乐(静安店),新闸路850号(近石门二路),韩国料理,BELLO'CO,4.8,口味: 8.4,人均: 154 元,五花肉:全州拌饭;四色饼;四色饼;奶酪鸡蛋卷;嫩豆腐汤;宫中拌猪排;宫中石锅拌饭;手握饭团;...
1,上海,Thai Gallery泰廊餐厅,南京西路1649号静安公园内,泰国菜,Thai Gallery,4.7,口味: 8.3,人均: 217 元,冬荫功;前餐拼盘;椰汁西米糕;椰汁香茅黄咖...;泰国椰皇;泰廊-冬阴功汤;泰廊特色海鲜.....
2,上海,青鹤谷(虹莘路总店),虹莘路3998号帝宝大厦2楼,韩国料理,"周二至周五 11:30-14:00 17:00-21:00 周六,周日 11:30-15:...",4.8,口味: 8.9,人均: 193 元,五花肉;全州拌饭;四色饼;大酱汤;奶酪鸡蛋卷;嫩豆腐汤;宫中拌猪排;宫中石锅拌饭;手握饭团;...
3,杭州,福缘居酒楼(河坊街店),河坊街35号(驾驶员培训中心旁),浙菜,周一至周日 11:00-14:00 16:30-21:00,4.2,口味: 8.3,人均: 105 元,三鲜汤;上汤菠菜;东坡肉(块);八宝油条;卤鸭;嫩菱芦笋;家常豆腐;干炸带鱼;干炸臭豆腐;望...
4,杭州,朴墅(青芝坞店),玉古路61-1号,浙菜,周一至周日 11:00-13:30 16:30-20:30,4.5,口味: 8.4,人均: 113 元,东洋手撕豆腐;人品大爆发;吱吱鲜芦笋;啫啫紫苏牛蛙;奶油芝士焗南瓜;嫩豌豆;干锅包心菜;年糕...
...,...,...,...,...,...,...,...,...,...
76,郑州,Two Birds One Stone·一石二鸟(木色店),商务内环路和通泰路交叉口永威木色购物公园西门一楼 L1-101,咖啡厅,"周一至周五 09:30-21:30 周六,周日 09:30-22:00",4.2,口味: 8.2,人均: 104 元,SINGHA...;三文鱼塔;三文鱼片牛油...;巴沙炸鱼薯条;意式肉酱面;招牌羊角班尼;水...
77,郑州,出云记(城东路店),城东路与城北路交叉口西50米路南(永利温泉酒店院内东侧),浙菜,周一至周日 11:30-14:30 17:30-21:30,4.5,口味: 8.8,人均: 95 元,出云辣子鸡;双椒扒茼蒿;咸蛋黄茄子;大杏仁炒菠菜;小罐泡馍;手撕包菜;招牌酸梅汤扎;杭州熏鱼...
78,重庆,二火锅(沙滨路总店),沙滨路11号附10号(财信沙滨城市内),重庆火锅,周一至周日 11:00-13:30 16:30-23:00,4.5,口味: 8.9,人均: 115 元,冰汤圆;孜然肉片;毛肚;滑肉;猪黄喉;现炸酥肉;红汤锅底;耗儿鱼;耙牛肉;耙鸡爪;脑花;腰片...
79,重庆,晓小面,洋河四路10号附8号,面馆,周一至周日 全天,4.5,口味: 8.7,人均: 15 元,加肥肠;北冰洋;原汤牛肉;干溜儿宽面;干溜炸酱面;干溜豌杂牛肉;干豌杂;晓小面;杂酱宽面;煎...
80,重庆,范嬢嬢春森路糯米团,学田湾正街59号春森路社区门口,小吃,周一至周日 09:30-17:00,4.5,口味: 8.7,人均: 6 元,八宝粥;卤蛋;团子;油茶;热乎乎的糯米;糍饭团;糯米团;糯米饭;脆油条;豆浆;银耳汤;银耳糯...

In [119]:
a1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81 entries, 0 to 80
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   城市      81 non-null     object
 1   门店名称    81 non-null     object
 2   地址      81 non-null     object
 3   品类      81 non-null     object
 4   营业时间    81 non-null     object
 5   门店整体评分  81 non-null     float64
 6   口味评分    81 non-null     object
 7   人均消费    81 non-null     object
 8   招牌菜     78 non-null     object
dtypes: float64(1), object(8)
memory usage: 5.8+ KB

In [120]:
a1.describe()

          门店整体评分
count  81.000000
mean    4.581481
std     0.213372
min     3.800000
25%     4.500000
50%     4.600000
75%     4.700000
max     4.900000

In [121]:
a1.dropna(axis=0,inplace=True)
a1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 78 entries, 0 to 80
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   城市      78 non-null     object
 1   门店名称    78 non-null     object
 2   地址      78 non-null     object
 3   品类      78 non-null     object
 4   营业时间    78 non-null     object
 5   门店整体评分  78 non-null     float64
 6   口味评分    78 non-null     object
 7   人均消费    78 non-null     object
 8   招牌菜     78 non-null     object
dtypes: float64(1), object(8)
memory usage: 6.1+ KB

In [122]:
import re

In [123]:
a1['口味评分']=a1['口味评分'].apply(lambda x:re.findall('\d+\.?\d*',x)[0]).astype('float')
a1

,城市,门店名称,地址,品类,营业时间,门店整体评分,口味评分,人均消费,招牌菜
0,上海,BELLOCO倍乐(静安店),新闸路850号(近石门二路),韩国料理,BELLO'CO,4.8,8.4,人均: 154 元,五花肉:全州拌饭;四色饼;四色饼;奶酪鸡蛋卷;嫩豆腐汤;宫中拌猪排;宫中石锅拌饭;手握饭团;...
1,上海,Thai Gallery泰廊餐厅,南京西路1649号静安公园内,泰国菜,Thai Gallery,4.7,8.3,人均: 217 元,冬荫功;前餐拼盘;椰汁西米糕;椰汁香茅黄咖...;泰国椰皇;泰廊-冬阴功汤;泰廊特色海鲜.....
2,上海,青鹤谷(虹莘路总店),虹莘路3998号帝宝大厦2楼,韩国料理,"周二至周五 11:30-14:00 17:00-21:00 周六,周日 11:30-15:...",4.8,8.9,人均: 193 元,五花肉;全州拌饭;四色饼;大酱汤;奶酪鸡蛋卷;嫩豆腐汤;宫中拌猪排;宫中石锅拌饭;手握饭团;...
3,杭州,福缘居酒楼(河坊街店),河坊街35号(驾驶员培训中心旁),浙菜,周一至周日 11:00-14:00 16:30-21:00,4.2,8.3,人均: 105 元,三鲜汤;上汤菠菜;东坡肉(块);八宝油条;卤鸭;嫩菱芦笋;家常豆腐;干炸带鱼;干炸臭豆腐;望...
4,杭州,朴墅(青芝坞店),玉古路61-1号,浙菜,周一至周日 11:00-13:30 16:30-20:30,4.5,8.4,人均: 113 元,东洋手撕豆腐;人品大爆发;吱吱鲜芦笋;啫啫紫苏牛蛙;奶油芝士焗南瓜;嫩豌豆;干锅包心菜;年糕...
...,...,...,...,...,...,...,...,...,...
76,郑州,Two Birds One Stone·一石二鸟(木色店),商务内环路和通泰路交叉口永威木色购物公园西门一楼 L1-101,咖啡厅,"周一至周五 09:30-21:30 周六,周日 09:30-22:00",4.2,8.2,人均: 104 元,SINGHA...;三文鱼塔;三文鱼片牛油...;巴沙炸鱼薯条;意式肉酱面;招牌羊角班尼;水...
77,郑州,出云记(城东路店),城东路与城北路交叉口西50米路南(永利温泉酒店院内东侧),浙菜,周一至周日 11:30-14:30 17:30-21:30,4.5,8.8,人均: 95 元,出云辣子鸡;双椒扒茼蒿;咸蛋黄茄子;大杏仁炒菠菜;小罐泡馍;手撕包菜;招牌酸梅汤扎;杭州熏鱼...
78,重庆,二火锅(沙滨路总店),沙滨路11号附10号(财信沙滨城市内),重庆火锅,周一至周日 11:00-13:30 16:30-23:00,4.5,8.9,人均: 115 元,冰汤圆;孜然肉片;毛肚;滑肉;猪黄喉;现炸酥肉;红汤锅底;耗儿鱼;耙牛肉;耙鸡爪;脑花;腰片...
79,重庆,晓小面,洋河四路10号附8号,面馆,周一至周日 全天,4.5,8.7,人均: 15 元,加肥肠;北冰洋;原汤牛肉;干溜儿宽面;干溜炸酱面;干溜豌杂牛肉;干豌杂;晓小面;杂酱宽面;煎...
80,重庆,范嬢嬢春森路糯米团,学田湾正街59号春森路社区门口,小吃,周一至周日 09:30-17:00,4.5,8.7,人均: 6 元,八宝粥;卤蛋;团子;油茶;热乎乎的糯米;糍饭团;糯米团;糯米饭;脆油条;豆浆;银耳汤;银耳糯...

In [124]:
a1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 78 entries, 0 to 80
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   城市      78 non-null     object
 1   门店名称    78 non-null     object
 2   地址      78 non-null     object
 3   品类      78 non-null     object
 4   营业时间    78 non-null     object
 5   门店整体评分  78 non-null     float64
 6   口味评分    78 non-null     float64
 7   人均消费    78 non-null     object
 8   招牌菜     78 non-null     object
dtypes: float64(2), object(7)
memory usage: 6.1+ KB

In [125]:
a1['人均消费']=a1['人均消费'].apply(lambda x:re.findall('\d+',x)[0]).astype('int')
a1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 78 entries, 0 to 80
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   城市      78 non-null     object
 1   门店名称    78 non-null     object
 2   地址      78 non-null     object
 3   品类      78 non-null     object
 4   营业时间    78 non-null     object
 5   门店整体评分  78 non-null     float64
 6   口味评分    78 non-null     float64
 7   人均消费    78 non-null     int64
 8   招牌菜     78 non-null     object
dtypes: float64(2), int64(1), object(6)
memory usage: 6.1+ KB

In [126]:
a2=a1.groupby('城市')['人均消费'].mean().sort_values(ascending=False).head(10)
a2

城市
大连    499.000000
上海    188.000000
长沙    142.000000
广州    136.666667
福州    132.000000
济南    118.666667
杭州    111.666667
苏州    101.666667
武汉    101.000000
北京    100.000000
Name: 人均消费, dtype: float64

In [127]:
bar = (
    # 主题
    Bar(init_opts=opts.InitOpts(theme='white',bg_color='rgba(255,182,193,0.4)'))
    .add_xaxis(a2.index.tolist())
    .add_yaxis("人均消费", a2.values.tolist())
    .set_global_opts(title_opts=opts.TitleOpts(title="个城市人均消费", subtitle="副标题"))
)
bar.load_javascript()
bar.render('./图例/1.html')

'D:\\桌面\\数据分析\\14大众点评案例\\图例\\1.html'

In [128]:
a3=a1.groupby('城市')['门店整体评分'].sum().sort_values(ascending=False).head(5)
a4=a3.rename(index={'上海':'上海市','福州':'福建省','深圳':"广东省",'沈阳':'辽宁省','苏州':'江苏省'})

In [129]:
map1 = Map()
map1.add("",[z for z in zip(a4.index.tolist(),[15,114,236,610,895])],maptype='china')
map1.set_global_opts(
    title_opts = opts.TitleOpts(title='大众点评国内各地美食评分分布图'),
    visualmap_opts = opts.VisualMapOpts(max_=900)
)
map1.load_javascript()
map1.render('./图例/3.html')

'D:\\桌面\\数据分析\\14大众点评案例\\图例\\3.html'

In [130]:
a1

,城市,门店名称,地址,品类,营业时间,门店整体评分,口味评分,人均消费,招牌菜
0,上海,BELLOCO倍乐(静安店),新闸路850号(近石门二路),韩国料理,BELLO'CO,4.8,8.4,154,五花肉:全州拌饭;四色饼;四色饼;奶酪鸡蛋卷;嫩豆腐汤;宫中拌猪排;宫中石锅拌饭;手握饭团;...
1,上海,Thai Gallery泰廊餐厅,南京西路1649号静安公园内,泰国菜,Thai Gallery,4.7,8.3,217,冬荫功;前餐拼盘;椰汁西米糕;椰汁香茅黄咖...;泰国椰皇;泰廊-冬阴功汤;泰廊特色海鲜.....
2,上海,青鹤谷(虹莘路总店),虹莘路3998号帝宝大厦2楼,韩国料理,"周二至周五 11:30-14:00 17:00-21:00 周六,周日 11:30-15:...",4.8,8.9,193,五花肉;全州拌饭;四色饼;大酱汤;奶酪鸡蛋卷;嫩豆腐汤;宫中拌猪排;宫中石锅拌饭;手握饭团;...
3,杭州,福缘居酒楼(河坊街店),河坊街35号(驾驶员培训中心旁),浙菜,周一至周日 11:00-14:00 16:30-21:00,4.2,8.3,105,三鲜汤;上汤菠菜;东坡肉(块);八宝油条;卤鸭;嫩菱芦笋;家常豆腐;干炸带鱼;干炸臭豆腐;望...
4,杭州,朴墅(青芝坞店),玉古路61-1号,浙菜,周一至周日 11:00-13:30 16:30-20:30,4.5,8.4,113,东洋手撕豆腐;人品大爆发;吱吱鲜芦笋;啫啫紫苏牛蛙;奶油芝士焗南瓜;嫩豌豆;干锅包心菜;年糕...
...,...,...,...,...,...,...,...,...,...
76,郑州,Two Birds One Stone·一石二鸟(木色店),商务内环路和通泰路交叉口永威木色购物公园西门一楼 L1-101,咖啡厅,"周一至周五 09:30-21:30 周六,周日 09:30-22:00",4.2,8.2,104,SINGHA...;三文鱼塔;三文鱼片牛油...;巴沙炸鱼薯条;意式肉酱面;招牌羊角班尼;水...
77,郑州,出云记(城东路店),城东路与城北路交叉口西50米路南(永利温泉酒店院内东侧),浙菜,周一至周日 11:30-14:30 17:30-21:30,4.5,8.8,95,出云辣子鸡;双椒扒茼蒿;咸蛋黄茄子;大杏仁炒菠菜;小罐泡馍;手撕包菜;招牌酸梅汤扎;杭州熏鱼...
78,重庆,二火锅(沙滨路总店),沙滨路11号附10号(财信沙滨城市内),重庆火锅,周一至周日 11:00-13:30 16:30-23:00,4.5,8.9,115,冰汤圆;孜然肉片;毛肚;滑肉;猪黄喉;现炸酥肉;红汤锅底;耗儿鱼;耙牛肉;耙鸡爪;脑花;腰片...
79,重庆,晓小面,洋河四路10号附8号,面馆,周一至周日 全天,4.5,8.7,15,加肥肠;北冰洋;原汤牛肉;干溜儿宽面;干溜炸酱面;干溜豌杂牛肉;干豌杂;晓小面;杂酱宽面;煎...
80,重庆,范嬢嬢春森路糯米团,学田湾正街59号春森路社区门口,小吃,周一至周日 09:30-17:00,4.5,8.7,6,八宝粥;卤蛋;团子;油茶;热乎乎的糯米;糍饭团;糯米团;糯米饭;脆油条;豆浆;银耳汤;银耳糯...

In [131]:
def parse(x):
    if x<50:
        return "50元以下"
    elif x<150:
        return "50元-150元之间"
    elif x<300:
        return "150元-300元之间"
    elif x<400:
        return "300元-400元之间"
    else:
        return '400元以上' 
a1['人均消费'].apply(lambda x:parse(x))

0     150元-300元之间
1     150元-300元之间
2     150元-300元之间
3      50元-150元之间
4      50元-150元之间
         ...
76     50元-150元之间
77     50元-150元之间
78     50元-150元之间
79          50元以下
80          50元以下
Name: 人均消费, Length: 78, dtype: object

In [132]:
pd.cut(a1['人均消费'],bins=[0,50,150,300,400,500])

0     (150, 300]
1     (150, 300]
2     (150, 300]
3      (50, 150]
4      (50, 150]
         ...
76     (50, 150]
77     (50, 150]
78     (50, 150]
79       (0, 50]
80       (0, 50]
Name: 人均消费, Length: 78, dtype: category
Categories (5, interval[int64, right]): [(0, 50] < (50, 150] < (150, 300] < (300, 400] < (400, 500]]

In [133]:
a1['人均消费区间']=a1['人均消费'].apply(lambda x:parse(x))
a1

,城市,门店名称,地址,品类,营业时间,门店整体评分,口味评分,人均消费,招牌菜,人均消费区间
0,上海,BELLOCO倍乐(静安店),新闸路850号(近石门二路),韩国料理,BELLO'CO,4.8,8.4,154,五花肉:全州拌饭;四色饼;四色饼;奶酪鸡蛋卷;嫩豆腐汤;宫中拌猪排;宫中石锅拌饭;手握饭团;...,150元-300元之间
1,上海,Thai Gallery泰廊餐厅,南京西路1649号静安公园内,泰国菜,Thai Gallery,4.7,8.3,217,冬荫功;前餐拼盘;椰汁西米糕;椰汁香茅黄咖...;泰国椰皇;泰廊-冬阴功汤;泰廊特色海鲜.....,150元-300元之间
2,上海,青鹤谷(虹莘路总店),虹莘路3998号帝宝大厦2楼,韩国料理,"周二至周五 11:30-14:00 17:00-21:00 周六,周日 11:30-15:...",4.8,8.9,193,五花肉;全州拌饭;四色饼;大酱汤;奶酪鸡蛋卷;嫩豆腐汤;宫中拌猪排;宫中石锅拌饭;手握饭团;...,150元-300元之间
3,杭州,福缘居酒楼(河坊街店),河坊街35号(驾驶员培训中心旁),浙菜,周一至周日 11:00-14:00 16:30-21:00,4.2,8.3,105,三鲜汤;上汤菠菜;东坡肉(块);八宝油条;卤鸭;嫩菱芦笋;家常豆腐;干炸带鱼;干炸臭豆腐;望...,50元-150元之间
4,杭州,朴墅(青芝坞店),玉古路61-1号,浙菜,周一至周日 11:00-13:30 16:30-20:30,4.5,8.4,113,东洋手撕豆腐;人品大爆发;吱吱鲜芦笋;啫啫紫苏牛蛙;奶油芝士焗南瓜;嫩豌豆;干锅包心菜;年糕...,50元-150元之间
...,...,...,...,...,...,...,...,...,...,...
76,郑州,Two Birds One Stone·一石二鸟(木色店),商务内环路和通泰路交叉口永威木色购物公园西门一楼 L1-101,咖啡厅,"周一至周五 09:30-21:30 周六,周日 09:30-22:00",4.2,8.2,104,SINGHA...;三文鱼塔;三文鱼片牛油...;巴沙炸鱼薯条;意式肉酱面;招牌羊角班尼;水...,50元-150元之间
77,郑州,出云记(城东路店),城东路与城北路交叉口西50米路南(永利温泉酒店院内东侧),浙菜,周一至周日 11:30-14:30 17:30-21:30,4.5,8.8,95,出云辣子鸡;双椒扒茼蒿;咸蛋黄茄子;大杏仁炒菠菜;小罐泡馍;手撕包菜;招牌酸梅汤扎;杭州熏鱼...,50元-150元之间
78,重庆,二火锅(沙滨路总店),沙滨路11号附10号(财信沙滨城市内),重庆火锅,周一至周日 11:00-13:30 16:30-23:00,4.5,8.9,115,冰汤圆;孜然肉片;毛肚;滑肉;猪黄喉;现炸酥肉;红汤锅底;耗儿鱼;耙牛肉;耙鸡爪;脑花;腰片...,50元-150元之间
79,重庆,晓小面,洋河四路10号附8号,面馆,周一至周日 全天,4.5,8.7,15,加肥肠;北冰洋;原汤牛肉;干溜儿宽面;干溜炸酱面;干溜豌杂牛肉;干豌杂;晓小面;杂酱宽面;煎...,50元以下
80,重庆,范嬢嬢春森路糯米团,学田湾正街59号春森路社区门口,小吃,周一至周日 09:30-17:00,4.5,8.7,6,八宝粥;卤蛋;团子;油茶;热乎乎的糯米;糍饭团;糯米团;糯米饭;脆油条;豆浆;银耳汤;银耳糯...,50元以下

In [134]:
s=a1['人均消费区间'].value_counts()
s

人均消费区间
50元-150元之间     62
150元-300元之间     8
50元以下           7
400元以上          1
Name: count, dtype: int64

In [135]:
bar3 = Bar() 
bar3.add_xaxis(s.index.tolist())
bar3.add_yaxis('', s.values.tolist()) 
bar3.set_global_opts(title_opts=opts.TitleOpts(title='大众点评人均消费不同价格区间情况'),
                     visualmap_opts=opts.VisualMapOpts(max_=65)) 
bar3.load_javascript()
bar3.render('./图例/4.html')

'D:\\桌面\\数据分析\\14大众点评案例\\图例\\4.html'

In [136]:
data_pair=[data_pair for data_pair in zip(s.index.tolist(),s.values.tolist())]
pie1 = Pie()
pie1.add('', data_pair, radius=['35%', '60%'])
pie1.set_global_opts(title_opts=opts.TitleOpts(title='大众点评不同价格区间人均消费的表现'), 
                     legend_opts=opts.LegendOpts(orient='vertical', pos_top='15%', pos_left='2%'))
pie1.set_series_opts(label_opts=opts.LabelOpts(formatter="{b}:{d}%"))
pie1.set_colors(['#EF9050', '#3B7BA9', '#6FB27C', '#FFAF34', '#D8BFD8', '#00BFFF', '#7FFFAA'])
pie1.load_javascript()
pie1.render('./图例/5.html')

'D:\\桌面\\数据分析\\14大众点评案例\\图例\\5.html'