In [1]:
import pandas as pd

In [2]:
df=pd.read_excel('总共酒店数据.xlsx')
df

,酒店名称,合并后评论,评论数量,酒店评分,最低价格,最高价格,酒店级别,城市级别,城市
0,\n乐乎酒店(北京对外经贸大学店),福** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,5.0 打分,\n¥279起\n,\n¥587起\n,三星,一线,北京
1,\n京玺酒店(北京国贸SKP店),如** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.8 打分,\n¥311起\n,\n¥626起\n,三星,一线,北京
2,\n京玺酒店(北京国贸劲松店),b** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.7 打分,\n¥362起\n,\n¥574起\n,三星,一线,北京
3,\n优轩酒店（南宁青秀山风景区万象城店）,h** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.9 打分,\n¥187起\n,\n¥255起\n,三星,一线,南宁
4,\n全季南宁火车站明秀东路酒店,四** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.9 打分,\n¥238起\n,\n¥312起\n,三星,一线,南宁
...,...,...,...,...,...,...,...,...,...
284,\n南宁龙光那莲豪华精选酒店,c** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.8 打分,\n¥881起\n,\n¥993起\n,五星,二线,南宁
285,\n广西沃顿国际大酒店,t** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,22,4.5 打分,\n¥450起\n,\n¥1309起\n,五星,二线,南宁
286,\n沃笙酒店(万象城南宁火车东站店),t** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.9 打分,\n¥421起\n,\n¥10162起\n,五星,二线,南宁
287,\n沃笙酒店(南宁江南旗舰店),r** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.9 打分,\n¥452起\n,\n¥11256起\n,五星,二线,南宁
288,\n金庆盛金钻酒店(万象城南宁火车东站店),p** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.5 打分,\n¥327起\n,\n¥2359起\n,五星,二线,南宁

In [3]:
df.合并后评论

0      福** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...
1      如** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...
2      b** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...
3      h** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...
4      四** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...
                             ...
284    c** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...
285    t** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...
286    t** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...
287    r** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...
288    p** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...
Name: 合并后评论, Length: 289, dtype: object

In [4]:
dimensions_keywords = {
    '清洁程度': {
        "positive":[
            "干净", "整洁", "无尘", "无灰", "透亮", "洁白", "清爽", "洁净",
            "崭新", "光洁", "除菌", "消毒", "无垢", "无水渍", "无毛发", "无污渍",
            "无霉斑", "无残渣", "无异味", "光亮", "一尘不染", "清扫彻底",
            "打扫细致", "边角干净", "床品雪白", "马桶光亮", "台面清爽",
            "瓷砖透亮", "通风干爽", "定时消杀", "垃圾清空", "缝隙无尘",
            "浴巾洁净", "拖鞋干净", "纱窗无尘", "窗台干净", "无手印",
            "无积水", "无皂垢", "全屋除菌", "焕然一新", "保洁到位"
        ],
        "nav":[
            "脏乱", "脏污", "积灰", "发霉", "黏腻", "发臭", "泛黄", "暗沉",
            "污渍多", "毛发多", "霉斑重", "水渍厚", "油污重", "有残渣", "有异味",
            "马桶垢", "垃圾满", "灰尘厚", "床品脏", "角落脏", "缝隙污",
            "保洁敷衍", "打扫潦草", "积水未清", "皂垢堆积", "墙面发黑",
            "地漏发臭", "地毯脏污", "镜面带印", "纱窗积灰", "遗留污垢",
            "遍地纸屑", "气味难闻", "消毒不足", "黏脚地面", "满是手印"
        ]
    },
    '地理位置': {
        'positive':[
            "位置佳", "地段好", "区位优", "黄金位", "市中心", "城中心", "核心区",
            "近地铁", "地铁口", "近高铁", "近车站", "近公交", "站点旁", "出行便",
            "交通顺", "通勤快", "多路公交", "打车方便", "打车就近", "自驾方便",
            "车位充足", "免费停车", "停车省事", "好找好找", "定位精准", "门头显眼",
            "近景区", "景点旁", "步行观景", "临公园", "临湖景", "临江景", "视野开阔",
            "无遮挡", "闹中取静", "不吵临街", "配套齐全", "楼下商超", "楼下餐饮",
            "楼下便利店", "楼下夜市", "步行街旁", "商场隔壁", "小吃众多", "生活便利",
            "办事顺路", "近写字楼", "近会展", "近医院", "近学校", "下楼散步",
            "短途可达", "出行省时", "区位便利", "地段绝佳", "出行无忧", "周边繁华"
        ],
        "nav":[
            "地段偏", "位置差", "区位差", "郊区远", "城郊荒", "人烟少", "周边荒",
            "离地铁远", "离车站远", "离景区远", "公交稀少", "班次很少", "打车困难",
            "难打车", "溢价打车", "车位紧张", "停车收费", "车位不足", "停车拥挤",
            "难找难找", "巷子幽深", "门头隐蔽", "定位不准", "绕路很远", "道路难行",
            "配套匮乏", "商铺稀少", "吃饭不便", "购物很远", "无便利店", "周边冷清",
            "临街嘈杂", "临近高架", "车流嘈杂", "货车吵闹", "楼下工地", "施工噪音",
            "视野很差", "楼房遮挡", "无景观", "窗户挡墙", "早晚堵车", "通勤耗时",
            "路灯稀少", "夜间冷清", "靠近垃圾站", "扬尘很大", "城中村深巷", "出行折腾"
        ]
    },
    '服务体验':{
        "positive":[
            "周到", "贴心", "热情", "细致", "专业", "高效", "耐心", "友善",
            "暖心", "温和", "主动", "及时", "快速", "温柔", "礼貌", "客气",
            "和善", "亲和", "热心", "尽责", "靠谱", "贴心", "周到", "体恤",
            "细心", "体贴", "周全", "爽快", "和善", "包容", "负责", "积极",
            "秒回", "秒响应", "免排队", "搬行李", "升房型", "延时退房",
            "寄存行李", "借雨伞", "借充电器", "送饮用水", "补给用品",
            "指引路线", "预约车辆", "代订门票", "耐心解答", "笑脸接待",
            "轻声打扫", "快速处理", "主动帮忙", "贴心提醒", "免费赠送",
            "随叫随到", "有求必应", "人性化", "宾至如归", "服务到位",
            "态度很好", "接待得体", "办事利索", "贴心管家", "安保贴心",
            "送餐迅速", "洗衣快捷", "主动补给", "主动引路", "售后负责",
            "不厌其烦", "笑脸相迎", "待人真诚", "响应及时", "办事顺畅"
        ],
        "nav":[
            "冷漠", "敷衍", "拖沓", "蛮横", "怠慢", "不耐烦", "无视", "推诿",
            "低效", "缓慢", "失联", "刁难", "吵闹", "加价", "推销", "顶撞",
            "傲慢", "冷淡", "敷衍", "懒散", "敷衍", "推诿", "推卸", "暴躁",
            "粗鲁", "生硬", "散漫", "消极", "摆脸", "无视客人", "爱答不理",
            "排队久", "不回应", "不补给", "漏叫醒", "拖延送物", "推卸责任",
            "隐形收费", "态度差", "素质低", "无人接待", "强行打扰", "置之不理",
            "办事拖拉", "推脱问题", "语气冲", "随意加价", "强制推销",
            "呼叫无人", "保洁吵闹", "私自翻物", "投诉不理", "百般刁难",
            "索要小费", "限制寄存", "拒绝延时", "打扫扰民", "一问三不知",
            "处理缓慢", "敷衍应付", "态度恶劣", "全程冷脸", "服务缺位"
        ]
    },
    '性价比':{
        'positive':[
            "划算", "实惠", "平价", "超值", "价廉", "公道", "亲民", "省钱",
            "捡漏", "物美", "不贵", "值当", "低价", "良心价", "实在价", "性价比高",
            "折扣大", "优惠多", "套餐值", "人均低", "定价实", "无溢价", "性价比满",
            "物有所值", "物超所值", "物美价廉", "低价高配", "花钱划算", "定价良心",
            "优惠给力", "团购划算", "套餐实惠", "同等最优", "价格友好", "性价比出众",
            "性价比超高", "性价比亮眼", "性价比到位", "花少享好", "不虚消费"
        ],
        'nav':[
            "不值", "太贵", "价高", "虚贵", "坑人", "宰客", "离谱", "不值当",
            "溢价重", "收费高", "定价坑", "漫天价", "价高质差", "低配高价",
            "定价离谱", "价格虚高", "溢价惊人", "收费虚高", "性价比低",
            "性价比差", "性价比拉胯", "性价比堪忧", "性价比垫底", "性价比翻车",
            "不值花费", "定价黑心", "溢价严重", "收费离谱", "同价位最差"
        ]
    }
}

In [5]:
import jieba

In [6]:
index=0
clean_score_list=[]
place_score_list=[]
serve_score_list=[]
price_score_list=[]
for i in df.groupby('酒店名称')['合并后评论']:
    lst=[j for j in i[1]]
    bar_len=len(lst)
    one_bar=''.join([j for j in i[1]])
    all_words=[word for word in jieba.cut(one_bar)]
    clean_score=0
    place_score=0
    serve_score=0
    price_score=0
    for w in all_words:
        if w in dimensions_keywords['清洁程度']['positive']:
            clean_score+=1
        if w in dimensions_keywords['清洁程度']['nav']:
            clean_score-=1
    clean_score=clean_score/bar_len
    for w in all_words:
        if w in dimensions_keywords['地理位置']['positive']:
            place_score+=1
        if w in dimensions_keywords['地理位置']['nav']:
            place_score-=1
    place_score=place_score/bar_len
    for w in all_words:
        if w in dimensions_keywords['服务体验']['positive']:
            serve_score+=1
        if w in dimensions_keywords['服务体验']['nav']:
            serve_score-=1
    serve_score=serve_score/bar_len
    for w in all_words:
        if w in dimensions_keywords['性价比']['positive']:
            price_score+=1
        if w in dimensions_keywords['性价比']['nav']:
            price_score-=1
    price_score=price_score/bar_len
    for len_ in range(bar_len):
        clean_score_list.append(clean_score)
        place_score_list.append(place_score)
        serve_score_list.append(serve_score)
        price_score_list.append(price_score)

Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\HUAWEI\AppData\Local\Temp\jieba.cache
Loading model cost 1.002 seconds.
Prefix dict has been built successfully.

In [7]:
df['clean_score']=pd.Series(data=clean_score_list)
df['place_score']=pd.Series(data=place_score_list)
df['serve_score']=pd.Series(data=serve_score_list)
df['price_score']=pd.Series(data=price_score_list)

In [8]:
df1=df.set_index(df['酒店名称'])
df1

,酒店名称,合并后评论,评论数量,酒店评分,最低价格,最高价格,酒店级别,城市级别,城市,clean_score,place_score,serve_score,price_score
酒店名称,,,,,,,,,,,,,
\n乐乎酒店(北京对外经贸大学店),\n乐乎酒店(北京对外经贸大学店),福** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,5.0 打分,\n¥279起\n,\n¥587起\n,三星,一线,北京,6.0,3.0,5.0,2.0
\n京玺酒店(北京国贸SKP店),\n京玺酒店(北京国贸SKP店),如** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.8 打分,\n¥311起\n,\n¥626起\n,三星,一线,北京,2.0,0.0,3.0,1.0
\n京玺酒店(北京国贸劲松店),\n京玺酒店(北京国贸劲松店),b** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.7 打分,\n¥362起\n,\n¥574起\n,三星,一线,北京,13.0,0.0,18.0,0.0
\n优轩酒店（南宁青秀山风景区万象城店）,\n优轩酒店（南宁青秀山风景区万象城店）,h** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.9 打分,\n¥187起\n,\n¥255起\n,三星,一线,南宁,3.0,4.0,12.0,0.0
\n全季南宁火车站明秀东路酒店,\n全季南宁火车站明秀东路酒店,四** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.9 打分,\n¥238起\n,\n¥312起\n,三星,一线,南宁,7.0,1.0,20.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
\n南宁龙光那莲豪华精选酒店,\n南宁龙光那莲豪华精选酒店,c** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.8 打分,\n¥881起\n,\n¥993起\n,五星,二线,南宁,11.0,0.0,9.0,0.0
\n广西沃顿国际大酒店,\n广西沃顿国际大酒店,t** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,22,4.5 打分,\n¥450起\n,\n¥1309起\n,五星,二线,南宁,3.0,1.0,5.0,1.0
\n沃笙酒店(万象城南宁火车东站店),\n沃笙酒店(万象城南宁火车东站店),t** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.9 打分,\n¥421起\n,\n¥10162起\n,五星,二线,南宁,9.0,0.0,12.0,0.0
\n沃笙酒店(南宁江南旗舰店),\n沃笙酒店(南宁江南旗舰店),r** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.9 打分,\n¥452起\n,\n¥11256起\n,五星,二线,南宁,10.0,1.0,12.0,2.0
\n金庆盛金钻酒店(万象城南宁火车东站店),\n金庆盛金钻酒店(万象城南宁火车东站店),p** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.5 打分,\n¥327起\n,\n¥2359起\n,五星,二线,南宁,1.0,0.0,5.0,0.0

In [9]:
df1.sort_values(by='clean_score',ascending=False)

,酒店名称,合并后评论,评论数量,酒店评分,最低价格,最高价格,酒店级别,城市级别,城市,clean_score,place_score,serve_score,price_score
酒店名称,,,,,,,,,,,,,
\n厦门佰翔波特曼七星湾酒店·瑞海,\n厦门佰翔波特曼七星湾酒店·瑞海,s** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.8 打分,\n¥849起\n,\n¥2703起\n,五星,二线,厦门,31.0,1.0,45.0,0.0
\n北京万达文华酒店,\n北京万达文华酒店,山** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,22,4.7 打分,\n¥1212起\n,\n¥104574起\n,五星,一线,北京,29.0,0.0,32.0,0.0
\n北京万达嘉华酒店,\n北京万达嘉华酒店,t** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.6 打分,\n¥636起\n,\n¥6770起\n,五星,一线,北京,29.0,0.0,32.0,0.0
\n成都领地希尔顿嘉悦里酒店,\n成都领地希尔顿嘉悦里酒店,清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★★★★★...,21,4.8 打分,\n¥667起\n,\n¥2313起\n,五星,新一线,成都,25.0,0.0,13.0,8.0
\n成都万达瑞华酒店（太古里店）,\n成都万达瑞华酒店（太古里店）,t** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.7 打分,\n¥799起\n,\n¥15718起\n,三星,新一线,成都,20.0,0.0,21.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
\n南宁天龙湾璞悦酒店,\n南宁天龙湾璞悦酒店,清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★★★★★...,21,4.8 打分,\n¥441起\n,\n¥2087起\n,五星,二线,南宁,0.0,0.0,1.0,6.0
\n喆啡酒店（北京肿瘤医院潘家园地铁站店）,\n喆啡酒店（北京肿瘤医院潘家园地铁站店）,泡** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.8 打分,\n¥332起\n,\n¥494起\n,三星,一线,北京,0.0,0.0,2.0,-1.0
\n厦门溪萌民宿,\n厦门溪萌民宿,t** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,50,5.0 打分,\n¥281起\n,\n¥380起\n,三星,二线,厦门,0.0,1.0,15.0,1.0
\n武汉富力万达嘉华酒店,\n武汉富力万达嘉华酒店,a** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.8 打分,\n¥539起\n,\n¥723起\n,五星,新一线,武汉,0.0,0.0,36.0,2.0
\n厦门鹭海影苑酒店（中山路店）,\n厦门鹭海影苑酒店（中山路店）,t** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,50,4.4 打分,\n¥149起\n,\n¥443起\n,三星,二线,厦门,0.0,0.0,7.0,0.0

In [10]:
df1.sort_values(by='place_score',ascending=False)

,酒店名称,合并后评论,评论数量,酒店评分,最低价格,最高价格,酒店级别,城市级别,城市,clean_score,place_score,serve_score,price_score
酒店名称,,,,,,,,,,,,,
\n厦门海港英迪格酒店(中山路店),\n厦门海港英迪格酒店(中山路店),h** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.8 打分,\n¥1072起\n,\n¥1801起\n,五星,二线,厦门,13.0,8.0,38.0,0.0
\n武汉新世界酒店,\n武汉新世界酒店,t** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.8 打分,\n¥438起\n,\n¥1166起\n,五星,新一线,武汉,13.0,8.0,11.0,0.0
\n厦门中心诺富特酒店,\n厦门中心诺富特酒店,f** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.7 打分,\n¥438起\n,\n¥798起\n,五星,二线,厦门,9.0,7.0,16.0,-6.0
\n厦门鹭海影苑酒店（中山路店）,\n厦门鹭海影苑酒店（中山路店）,t** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.4 打分,\n¥149起\n,\n¥443起\n,三星,二线,厦门,10.0,5.0,24.0,1.0
\n北京海淀稻香湖希尔顿花园酒店,\n北京海淀稻香湖希尔顿花园酒店,t** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.9 打分,\n¥549起\n,\n¥898起\n,五星,一线,北京,16.0,5.0,-1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
\n艾干酒店(宽窄巷子西南财大地铁站店),\n艾干酒店(宽窄巷子西南财大地铁站店),m** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.9 打分,\n¥208起\n,\n¥255起\n,三星,新一线,成都,8.0,0.0,7.0,1.0
\n四川岷山饭店,\n四川岷山饭店,唐** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.7 打分,\n¥509起\n,\n¥557起\n,五星,新一线,成都,11.0,0.0,15.0,1.0
\n四川锦江宾馆,\n四川锦江宾馆,短** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.8 打分,\n¥309起\n,\n¥1259起\n,五星,新一线,成都,7.0,0.0,8.0,2.0
\n成都W酒店,\n成都W酒店,哎** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.5 打分,\n¥1262起\n,\n¥8303起\n,五星,新一线,成都,13.0,0.0,32.0,1.0
\n金庆盛金钻酒店(万象城南宁火车东站店),\n金庆盛金钻酒店(万象城南宁火车东站店),p** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.5 打分,\n¥327起\n,\n¥2359起\n,五星,二线,南宁,1.0,0.0,5.0,0.0

In [11]:
df1.sort_values(by='serve_score',ascending=False)

,酒店名称,合并后评论,评论数量,酒店评分,最低价格,最高价格,酒店级别,城市级别,城市,clean_score,place_score,serve_score,price_score
酒店名称,,,,,,,,,,,,,
\n厦门凯斯特别墅酒店(环岛路曾厝垵店),\n厦门凯斯特别墅酒店(环岛路曾厝垵店),刘** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.7 打分,\n¥173起\n,\n¥852起\n,三星,二线,厦门,9.0,0.0,65.0,3.0
\n维也纳3好酒店（哈尔滨师范大学店）,\n维也纳3好酒店（哈尔滨师范大学店）,t** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.7 打分,\n¥222起\n,\n¥334起\n,三星,二线,哈尔滨,10.0,2.0,62.0,0.0
\nAMIX安迷酒店(黄鹤楼长江大桥店),\nAMIX安迷酒店(黄鹤楼长江大桥店),l** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,5.0 打分,\n¥226起\n,\n¥622起\n,三星,新一线,武汉,7.0,0.0,59.0,1.0
\n厦门山野故事·山海度假智能酒店（环岛路店）,\n厦门山野故事·山海度假智能酒店（环岛路店）,清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★★★★★...,21,4.9 打分,\n¥478起\n,\n¥710起\n,三星,二线,厦门,11.0,2.0,58.0,0.0
\n成都瑞吉酒店,\n成都瑞吉酒店,t** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.8 打分,\n¥946起\n,\n¥57710起\n,五星,新一线,成都,6.0,0.0,54.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
\n北京励骏酒店,\n北京励骏酒店,q** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.7 打分,\n¥948起\n,\n¥6183起\n,五星,一线,北京,6.0,0.0,0.0,1.0
\n哈尔滨璞砚酒店,\n哈尔滨璞砚酒店,逗** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.7 打分,\n¥960起\n,\n¥1217起\n,五星,二线,哈尔滨,2.0,0.0,0.0,1.0
\n和栖酒店(北京鸟巢安贞医院店),\n和栖酒店(北京鸟巢安贞医院店),e** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.7 打分,\n¥260起\n,\n¥420起\n,三星,一线,北京,2.0,1.0,0.0,1.0
\n南宁君豪逸园酒店（青秀山东门保利领秀店）,\n南宁君豪逸园酒店（青秀山东门保利领秀店）,l** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,22,4.8 打分,\n¥204起\n,\n¥271起\n,三星,一线,北京,10.0,4.0,0.0,0.0
\n北京海淀稻香湖希尔顿花园酒店,\n北京海淀稻香湖希尔顿花园酒店,t** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.9 打分,\n¥549起\n,\n¥898起\n,五星,一线,北京,16.0,5.0,-1.0,1.0

In [12]:
df1.sort_values(by='price_score',ascending=False)

,酒店名称,合并后评论,评论数量,酒店评分,最低价格,最高价格,酒店级别,城市级别,城市,clean_score,place_score,serve_score,price_score
酒店名称,,,,,,,,,,,,,
\n成都领地希尔顿嘉悦里酒店,\n成都领地希尔顿嘉悦里酒店,清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★★★★★...,21,4.8 打分,\n¥667起\n,\n¥2313起\n,五星,新一线,成都,25.0,0.0,13.0,8.0
\n柏曼酒店南宁朝阳步行街三街两巷店,\n柏曼酒店南宁朝阳步行街三街两巷店,d** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.9 打分,\n¥319起\n,\n¥589起\n,三星,二线,南宁,12.0,0.0,14.0,7.0
\n南宁天龙湾璞悦酒店,\n南宁天龙湾璞悦酒店,清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★★★★★...,21,4.8 打分,\n¥441起\n,\n¥2087起\n,五星,二线,南宁,0.0,0.0,1.0,6.0
\n紫藤树下客栈(成都宽窄巷子店),\n紫藤树下客栈(成都宽窄巷子店),哥** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.5 打分,\n¥97起\n,\n¥150起\n,三星,新一线,成都,15.0,0.0,7.0,5.0
\n厦门我们三民宿山河与海店,\n厦门我们三民宿山河与海店,t** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,22,4.9 打分,\n¥158起\n,\n¥3786起\n,三星,二线,厦门,15.0,2.0,8.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
\n南宁红林大酒店,\n南宁红林大酒店,清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★★★★★...,21,4.5 打分,\n¥452起\n,\n¥10533起\n,五星,二线,南宁,3.0,0.0,8.0,-3.0
\n凯里亚德酒店哈尔滨西站万达广场店,\n凯里亚德酒店哈尔滨西站万达广场店,c** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.7 打分,\n¥331起\n,\n¥318起\n,三星,二线,哈尔滨,3.0,0.0,8.0,-3.0
\n厦门集美杏林湾希尔顿欢朋酒店,\n厦门集美杏林湾希尔顿欢朋酒店,有** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.8 打分,\n¥475起\n,\n¥440起\n,五星,二线,厦门,2.0,0.0,9.0,-3.0
\n成都海湾酒店,\n成都海湾酒店,v** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.9 打分,\n¥911起\n,\n¥1563起\n,三星,新一线,成都,6.0,0.0,23.0,-3.0
\n厦门中心诺富特酒店,\n厦门中心诺富特酒店,f** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.7 打分,\n¥438起\n,\n¥798起\n,五星,二线,厦门,9.0,7.0,16.0,-6.0

In [13]:
df['total_score']=df['clean_score']+df['place_score']+df['serve_score']+df['price_score']
df

,酒店名称,合并后评论,评论数量,酒店评分,最低价格,最高价格,酒店级别,城市级别,城市,clean_score,place_score,serve_score,price_score,total_score
0,\n乐乎酒店(北京对外经贸大学店),福** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,5.0 打分,\n¥279起\n,\n¥587起\n,三星,一线,北京,6.0,3.0,5.0,2.0,16.0
1,\n京玺酒店(北京国贸SKP店),如** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.8 打分,\n¥311起\n,\n¥626起\n,三星,一线,北京,2.0,0.0,3.0,1.0,6.0
2,\n京玺酒店(北京国贸劲松店),b** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.7 打分,\n¥362起\n,\n¥574起\n,三星,一线,北京,13.0,0.0,18.0,0.0,31.0
3,\n优轩酒店（南宁青秀山风景区万象城店）,h** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.9 打分,\n¥187起\n,\n¥255起\n,三星,一线,南宁,3.0,4.0,12.0,0.0,19.0
4,\n全季南宁火车站明秀东路酒店,四** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.9 打分,\n¥238起\n,\n¥312起\n,三星,一线,南宁,7.0,1.0,20.0,2.0,30.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284,\n南宁龙光那莲豪华精选酒店,c** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.8 打分,\n¥881起\n,\n¥993起\n,五星,二线,南宁,11.0,0.0,9.0,0.0,20.0
285,\n广西沃顿国际大酒店,t** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,22,4.5 打分,\n¥450起\n,\n¥1309起\n,五星,二线,南宁,3.0,1.0,5.0,1.0,10.0
286,\n沃笙酒店(万象城南宁火车东站店),t** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.9 打分,\n¥421起\n,\n¥10162起\n,五星,二线,南宁,9.0,0.0,12.0,0.0,21.0
287,\n沃笙酒店(南宁江南旗舰店),r** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.9 打分,\n¥452起\n,\n¥11256起\n,五星,二线,南宁,10.0,1.0,12.0,2.0,25.0
288,\n金庆盛金钻酒店(万象城南宁火车东站店),p** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.5 打分,\n¥327起\n,\n¥2359起\n,五星,二线,南宁,1.0,0.0,5.0,0.0,6.0

In [14]:
df.drop_duplicates(subset=["酒店名称"], keep="first",inplace=True)

In [15]:
data=df.sort_values('total_score',ascending=False).head(8)

In [16]:
data

,酒店名称,合并后评论,评论数量,酒店评分,最低价格,最高价格,酒店级别,城市级别,城市,clean_score,place_score,serve_score,price_score,total_score
221,\n厦门凯斯特别墅酒店(环岛路曾厝垵店),刘** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.7 打分,\n¥173起\n,\n¥852起\n,三星,二线,厦门,9.0,0.0,65.0,3.0,77.0
195,\n厦门佰翔波特曼七星湾酒店·瑞海,s** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.8 打分,\n¥849起\n,\n¥2703起\n,五星,二线,厦门,31.0,1.0,45.0,0.0,77.0
184,\n维也纳3好酒店（哈尔滨师范大学店）,t** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.7 打分,\n¥222起\n,\n¥334起\n,三星,二线,哈尔滨,10.0,2.0,62.0,0.0,74.0
222,\n厦门山野故事·山海度假智能酒店（环岛路店）,清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★★★★★...,21,4.9 打分,\n¥478起\n,\n¥710起\n,三星,二线,厦门,11.0,2.0,58.0,0.0,71.0
46,\nAMIX安迷酒店(黄鹤楼长江大桥店),l** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,5.0 打分,\n¥226起\n,\n¥622起\n,三星,新一线,武汉,7.0,0.0,59.0,1.0,67.0
39,\n北京港澳中心瑞士酒店,a** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.7 打分,\n¥800起\n,\n¥3734起\n,五星,一线,北京,15.0,1.0,51.0,0.0,67.0
21,\n北京万达嘉华酒店,t** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,21,4.6 打分,\n¥636起\n,\n¥6770起\n,五星,一线,北京,29.0,0.0,32.0,0.0,61.0
22,\n北京万达文华酒店,山** 清洁程度:★★★★★★★★★★ 地理位置:★★★★★★★★★★ 服务体验:★★★★★...,22,4.7 打分,\n¥1212起\n,\n¥104574起\n,五星,一线,北京,29.0,0.0,32.0,0.0,61.0

In [17]:
from pyecharts.charts import *
from pyecharts.globals import ThemeType
from pyecharts import options as opts
from pyecharts.globals import CurrentConfig,NotebookType
CurrentConfig.NOTEBOOK_TYPE=NotebookType.JUPYTER_LAB

In [18]:
x=data['酒店名称'].tolist()
x

['\n厦门凯斯特别墅酒店(环岛路曾厝垵店)',
 '\n厦门佰翔波特曼七星湾酒店·瑞海',
 '\n维也纳3好酒店（哈尔滨师范大学店）',
 '\n厦门山野故事·山海度假智能酒店（环岛路店）',
 '\nAMIX安迷酒店(黄鹤楼长江大桥店)',
 '\n北京港澳中心瑞士酒店',
 '\n北京万达嘉华酒店',
 '\n北京万达文华酒店']

In [21]:
y=data['total_score'].tolist()
y

[77.0, 77.0, 74.0, 71.0, 67.0, 67.0, 61.0, 61.0]

In [22]:
pie=(
    Pie(init_opts=opts.InitOpts(width='800px',height='600px'))
    .add('前8名酒店总评分',[z for z in zip(x,y)],radius=['20%','45%'])
    .set_series_opts(label_opts=opts.LabelOpts(formatter='{b}:{d}%'))
    .set_global_opts(legend_opts=opts.LegendOpts(pos_bottom='5%',pos_right='5%'))
)
pie.load_javascript()

In [23]:
pie.render('score.html')

'D:\\桌面\\Bypass(1)\\score.html'